// Package codegen provides code generation from schemas.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"unicode"

	"github.com/nexus-db/nexus/pkg/core/schema"
)

// Generator generates Go code from schemas.
type Generator struct {
	schema      *schema.Schema
	packageName string
	outputDir   string
}

// NewGenerator creates a new code generator.
func NewGenerator(s *schema.Schema, packageName, outputDir string) *Generator {
	return &Generator{
		schema:      s,
		packageName: packageName,
		outputDir:   outputDir,
	}
}

// Generate generates Go code for all models.
func (g *Generator) Generate() error {
	if err := os.MkdirAll(g.outputDir, 0755); err != nil {
		return err
	}

	// Generate models file
	if err := g.generateModels(); err != nil {
		return err
	}

	// Generate queries file
	if err := g.generateQueries(); err != nil {
		return err
	}

	return nil
}

func (g *Generator) generateModels() error {
	tmpl := `// Code generated by Nexus. DO NOT EDIT.
package {{.PackageName}}

import (
	"time"
)

// Suppress unused import warning
var _ = time.Now

{{range .Models}}
// {{.Name}} represents a row in the {{.Name}} table.
type {{.Name}} struct {
{{- range .Fields}}
	{{goFieldName .Name}} {{goType .}} ` + "`" + `json:"{{.Name}}" db:"{{.Name}}"` + "`" + `
{{- end}}
}

// TableName returns the table name for {{.Name}}.
func ({{.Name}}) TableName() string {
	return "{{.Name}}"
}
{{end}}
`

	t, err := template.New("models").Funcs(template.FuncMap{
		"goFieldName": goFieldName,
		"goType":      goType,
	}).Parse(tmpl)
	if err != nil {
		return err
	}

	data := struct {
		PackageName string
		Models      []*schema.Model
	}{
		PackageName: g.packageName,
		Models:      g.schema.GetModels(),
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// If formatting fails, write unformatted
		formatted = buf.Bytes()
	}

	return os.WriteFile(filepath.Join(g.outputDir, "models.go"), formatted, 0644)
}

func (g *Generator) generateQueries() error {
	tmpl := `// Code generated by Nexus. DO NOT EDIT.
package {{.PackageName}}

import (
	"context"

	"github.com/nexus-db/nexus/pkg/dialects"
	"github.com/nexus-db/nexus/pkg/query"
)

// DB wraps a database connection with type-safe query methods.
type DB struct {
	conn *dialects.Connection
}

// NewDB creates a new DB wrapper.
func NewDB(conn *dialects.Connection) *DB {
	return &DB{conn: conn}
}

{{range .Models}}
// {{.Name}}Query returns a query builder for {{.Name}}.
func (db *DB) {{.Name}}Query() *query.Builder {
	return query.New(db.conn, "{{.Name}}")
}

// Create{{.Name}} inserts a new {{.Name}} record.
func (db *DB) Create{{.Name}}(ctx context.Context, data map[string]interface{}) (query.Result, error) {
	return db.{{.Name}}Query().Insert(data).Returning("*").One(ctx)
}

// Find{{.Name}}ByID finds a {{.Name}} by ID.
func (db *DB) Find{{.Name}}ByID(ctx context.Context, id interface{}) (query.Result, error) {
	return db.{{.Name}}Query().Select().Where(query.Eq("id", id)).One(ctx)
}

// FindAll{{.Name}}s returns all {{.Name}} records.
func (db *DB) FindAll{{.Name}}s(ctx context.Context) (query.Results, error) {
	return db.{{.Name}}Query().Select().All(ctx)
}

// Update{{.Name}} updates a {{.Name}} by ID.
func (db *DB) Update{{.Name}}(ctx context.Context, id interface{}, data map[string]interface{}) (int64, error) {
	return db.{{.Name}}Query().Update(data).Where(query.Eq("id", id)).Exec(ctx)
}

// Delete{{.Name}} deletes a {{.Name}} by ID.
func (db *DB) Delete{{.Name}}(ctx context.Context, id interface{}) (int64, error) {
	return db.{{.Name}}Query().Delete().Where(query.Eq("id", id)).Exec(ctx)
}
{{end}}
`

	t, err := template.New("queries").Parse(tmpl)
	if err != nil {
		return err
	}

	data := struct {
		PackageName string
		Models      []*schema.Model
	}{
		PackageName: g.packageName,
		Models:      g.schema.GetModels(),
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// If formatting fails, write unformatted
		formatted = buf.Bytes()
	}

	return os.WriteFile(filepath.Join(g.outputDir, "queries.go"), formatted, 0644)
}

// goFieldName converts a database column name to a Go field name.
func goFieldName(name string) string {
	// Convert snake_case to PascalCase
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if len(part) > 0 {
			runes := []rune(part)
			runes[0] = unicode.ToUpper(runes[0])
			parts[i] = string(runes)
		}
	}
	return strings.Join(parts, "")
}

// goType returns the Go type for a schema field.
func goType(field *schema.Field) string {
	var baseType string
	switch field.Type {
	case schema.FieldTypeInt:
		baseType = "int"
	case schema.FieldTypeBigInt:
		baseType = "int64"
	case schema.FieldTypeString, schema.FieldTypeText, schema.FieldTypeUUID:
		baseType = "string"
	case schema.FieldTypeBool:
		baseType = "bool"
	case schema.FieldTypeFloat:
		baseType = "float64"
	case schema.FieldTypeDecimal:
		baseType = "float64" // Could use decimal package
	case schema.FieldTypeDateTime, schema.FieldTypeDate, schema.FieldTypeTime:
		baseType = "time.Time"
	case schema.FieldTypeJSON:
		baseType = "json.RawMessage" // Or map[string]interface{}
	case schema.FieldTypeBytes:
		baseType = "[]byte"
	default:
		baseType = "interface{}"
	}

	if field.Nullable {
		// Use pointer for nullable types
		if baseType == "string" || baseType == "[]byte" {
			return "*" + baseType
		}
		return "*" + baseType
	}
	return baseType
}

// GenerateConfig represents code generation configuration.
type GenerateConfig struct {
	SchemaPath  string
	OutputDir   string
	PackageName string
}

// Run runs the code generator with the given config.
func Run(config GenerateConfig) error {
	// Parse schema
	s, err := schema.ParseFile(config.SchemaPath)
	if err != nil {
		return fmt.Errorf("parsing schema: %w", err)
	}

	// Validate schema
	if err := s.Validate(); err != nil {
		return fmt.Errorf("validating schema: %w", err)
	}

	// Generate code
	gen := NewGenerator(s, config.PackageName, config.OutputDir)
	return gen.Generate()
}
